###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401,F821
# flake8: noqa: E501,F401,F821
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class BulletPoints(BaseModel):
    points: List[str]
    mainIdea: str
    complexity: Union[Literal["basic"], Literal["intermediate"], Literal["advanced"]]

class ChatMessage(BaseModel):
    role: Union[Literal["user"], Literal["assistant"]]
    content: str
    timestamp: str

class ChatResponse(BaseModel):
    answer: str
    usedContext: List["ContextSource"]
    confidence: Union[Literal["high"], Literal["medium"], Literal["low"]]

class ContextSource(BaseModel):
    sourceType: Union[Literal["vector_db"], Literal["document"], Literal["api"]]
    content: str
    relevanceScore: float

class FinalResponse(BaseModel):
    answer: str
    queryUsed: str
    rawResults: str

class GraphQuery(BaseModel):
    query: str

class GraphResult(BaseModel):
    result: str

class GraphSchema(BaseModel):
    nodes: List[str]
    relationships: List[str]
    properties: List[str]

class Resume(BaseModel):
    name: str
    email: str
    experience: List[str]
    skills: List[str]
